version: "3"
services:
  domain:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      # 配置域名
      - "traefik.http.routers.cra.rule=Host(`cra.jinghonggang.fun`)"
      # 配置 TLS
#      - traefik.http.routers.cra.tls=true
#      - traefik.http.routers.cra.tls.certresolver=le